[package]
name = "icrc_wallet"
version = "0.1.0"
edition = "2021"

[dependencies]
candid = "0.9.9"
ic-cdk = "0.11.1"
ic-cdk-macros = "0.8.1"
icrc-ledger-types = "0.1.1"
serde = { version = "1.0", features = ["derive"] }

[lib]
crate-type = ["cdylib"]